/* Copyright (c) 2012 Rick (rick 'at' gibbed 'dot' us)
 * 
 * This software is provided 'as-is', without any express or implied
 * warranty. In no event will the authors be held liable for any damages
 * arising from the use of this software.
 * 
 * Permission is granted to anyone to use this software for any purpose,
 * including commercial applications, and to alter it and redistribute it
 * freely, subject to the following restrictions:
 * 
 * 1. The origin of this software must not be misrepresented; you must not
 *    claim that you wrote the original software. If you use this software
 *    in a product, an acknowledgment in the product documentation would
 *    be appreciated but is not required.
 * 
 * 2. Altered source versions must be plainly marked as such, and must not
 *    be misrepresented as being the original software.
 * 
 * 3. This notice may not be removed or altered from any source
 *    distribution.
 */

namespace Gibbed.Avalanche.ModelViewer2
{
    internal class ReferenceSkeleton
    {
        public static readonly ShaderNatives.float3x4[] Data = new[]
        {
            new ShaderNatives.float3x4(0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 1.0f, 1.0f, 0.0f),
            new ShaderNatives.float3x4(0.0f, 0.948133f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 1.0f, 1.0f, 0.0f),
            new ShaderNatives.float3x4(0.0f, 0.153544f, -0.005307f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 1.0f, 1.0f, 0.0f)
            ,
            new ShaderNatives.float3x4(-0.0f, 0.125565f, 0.001251f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 1.0f, 1.0f, 0.0f)
            ,
            new ShaderNatives.float3x4(-0.091283f,
                                       0.009014f,
                                       -0.015312f,
                                       0.0f,
                                       0.0f,
                                       0.0f,
                                       0.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       0.0f),
            new ShaderNatives.float3x4(0.000149f,
                                       -0.24195f,
                                       -0.003613f,
                                       0.0f,
                                       0.0f,
                                       -0.0f,
                                       -0.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       0.0f),
            new ShaderNatives.float3x4(0.000134f,
                                       -0.217024f,
                                       -0.003241f,
                                       0.0f,
                                       -0.0f,
                                       0.0f,
                                       0.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       0.0f),
            new ShaderNatives.float3x4(0.091283f,
                                       0.009014f,
                                       -0.015312f,
                                       0.0f,
                                       0.0f,
                                       -0.0f,
                                       -0.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       0.0f),
            new ShaderNatives.float3x4(-0.000149f,
                                       -0.24195f,
                                       -0.003613f,
                                       0.0f,
                                       -0.0f,
                                       0.0f,
                                       0.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       0.0f),
            new ShaderNatives.float3x4(-0.000134f,
                                       -0.217023f,
                                       -0.003241f,
                                       0.0f,
                                       0.0f,
                                       -0.0f,
                                       0.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       0.0f),
            new ShaderNatives.float3x4(-0.039689f,
                                       0.24057f,
                                       0.044774f,
                                       0.0f,
                                       0.0f,
                                       0.0f,
                                       0.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       0.0f),
            new ShaderNatives.float3x4(-0.16f,
                                       0.012302f,
                                       -0.000718f,
                                       0.0f,
                                       -0.0f,
                                       -0.0f,
                                       0.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       0.0f),
            new ShaderNatives.float3x4(-0.126972f,
                                       -0.008102f,
                                       0.0005f,
                                       0.0f,
                                       0.0f,
                                       0.0f,
                                       0.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       0.0f),
            new ShaderNatives.float3x4(-0.131972f,
                                       -0.008102f,
                                       0.0005f,
                                       0.0f,
                                       0.0f,
                                       0.0f,
                                       -0.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       0.0f),
            new ShaderNatives.float3x4(0.039689f,
                                       0.24057f,
                                       0.044774f,
                                       0.0f,
                                       0.0f,
                                       0.0f,
                                       0.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       0.0f),
            new ShaderNatives.float3x4(0.16f,
                                       0.012302f,
                                       -0.000718f,
                                       0.0f,
                                       -0.0f,
                                       0.0f,
                                       0.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       0.0f),
            new ShaderNatives.float3x4(0.126971f,
                                       -0.008101f,
                                       0.0005f,
                                       0.0f,
                                       0.0f,
                                       0.0f,
                                       -0.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       0.0f),
            new ShaderNatives.float3x4(0.131972f,
                                       -0.008101f,
                                       0.0005f,
                                       0.0f,
                                       0.0f,
                                       -0.0f,
                                       0.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       0.0f),
            new ShaderNatives.float3x4(-0.0f, 0.301246f, 0.044667f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 1.0f, 1.0f, 0.0f)
            ,
            new ShaderNatives.float3x4(0.0f, 0.116693f, -0.006886f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 1.0f, 1.0f, 0.0f)
            ,
            new ShaderNatives.float3x4(-0.105737f, 0.0f, 0.0f, 0.0f, -0.0f, -0.0f, 0.0f, 1.0f, 1.0f, 1.0f, 1.0f, 0.0f),
            new ShaderNatives.float3x4(0.105738f, 0.0f, 0.0f, 0.0f, -0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 1.0f, 1.0f, 0.0f),
            new ShaderNatives.float3x4(-0.125193f,
                                       -0.001222f,
                                       0.000718f,
                                       0.0f,
                                       0.0f,
                                       0.0f,
                                       0.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       0.0f),
            new ShaderNatives.float3x4(0.12328f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 1.0f, 1.0f, 0.0f),
            new ShaderNatives.float3x4(-0.062462f,
                                       -0.02838f,
                                       0.0f,
                                       0.0f,
                                       -0.0f,
                                       0.0f,
                                       0.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       0.0f),
            new ShaderNatives.float3x4(0.062462f, -0.02838f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 1.0f, 1.0f, 0.0f)
            ,
            new ShaderNatives.float3x4(0.0f, -0.26078f, 0.035653f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 1.0f, 1.0f, 0.0f)
            ,
            new ShaderNatives.float3x4(0.0f, -0.260779f, 0.035653f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 1.0f, 1.0f, 0.0f)
            ,
            new ShaderNatives.float3x4(0.0f, -0.173189f, 0.023678f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 1.0f, 1.0f, 0.0f)
            ,
            new ShaderNatives.float3x4(0.0f, -0.17319f, 0.023678f, 0.0f, -0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 1.0f, 1.0f, 0.0f)
            ,
            new ShaderNatives.float3x4(0.0f,
                                       -0.004159f,
                                       -0.049195f,
                                       0.0f,
                                       0.0f,
                                       0.0f,
                                       0.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       0.0f),
            new ShaderNatives.float3x4(0.100973f,
                                       0.00209f,
                                       -0.039497f,
                                       0.0f,
                                       0.0f,
                                       0.0f,
                                       -0.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       0.0f),
            new ShaderNatives.float3x4(-0.100973f,
                                       0.00209f,
                                       -0.039497f,
                                       0.0f,
                                       -0.0f,
                                       0.0f,
                                       -0.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       0.0f),
            new ShaderNatives.float3x4(0.031926f,
                                       0.0f,
                                       -0.003844f,
                                       0.0f,
                                       0.0f,
                                       -0.0f,
                                       0.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       0.0f),
            new ShaderNatives.float3x4(-0.031926f,
                                       0.0f,
                                       -0.003844f,
                                       0.0f,
                                       0.0f,
                                       -0.0f,
                                       0.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       0.0f),
            new ShaderNatives.float3x4(0.021442f, 0.0f, -0.001508f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 1.0f, 1.0f, 0.0f)
            ,
            new ShaderNatives.float3x4(-0.021442f,
                                       0.0f,
                                       -0.001508f,
                                       0.0f,
                                       -0.0f,
                                       -0.0f,
                                       -0.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       0.0f),
            new ShaderNatives.float3x4(0.106135f,
                                       0.00381f,
                                       -0.016974f,
                                       0.0f,
                                       0.0f,
                                       0.0f,
                                       0.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       0.0f),
            new ShaderNatives.float3x4(0.092288f,
                                       -0.00514f,
                                       0.027577f,
                                       0.0f,
                                       0.0f,
                                       0.0f,
                                       0.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       0.0f),
            new ShaderNatives.float3x4(0.102604f,
                                       0.00042f,
                                       0.006818f,
                                       0.0f,
                                       0.0f,
                                       -0.0f,
                                       0.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       0.0f),
            new ShaderNatives.float3x4(0.035762f,
                                       -0.01616f,
                                       -0.028581f,
                                       0.0f,
                                       -0.0f,
                                       0.0f,
                                       0.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       0.0f),
            new ShaderNatives.float3x4(-0.106135f,
                                       0.00381f,
                                       -0.016974f,
                                       0.0f,
                                       0.0f,
                                       0.0f,
                                       -0.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       0.0f),
            new ShaderNatives.float3x4(-0.092288f,
                                       -0.00514f,
                                       0.027577f,
                                       0.0f,
                                       0.0f,
                                       0.0f,
                                       0.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       0.0f),
            new ShaderNatives.float3x4(-0.102604f,
                                       0.00042f,
                                       0.006818f,
                                       0.0f,
                                       0.0f,
                                       0.0f,
                                       0.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       0.0f),
            new ShaderNatives.float3x4(-0.035762f,
                                       -0.01616f,
                                       -0.028581f,
                                       0.0f,
                                       0.0f,
                                       -0.0f,
                                       0.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       0.0f),
            new ShaderNatives.float3x4(0.03279f, 0.0f, -0.000142f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 1.0f, 1.0f, 0.0f)
            ,
            new ShaderNatives.float3x4(0.01986f,
                                       0.0f,
                                       0.002514f,
                                       0.0f,
                                       -0.0f,
                                       -0.0f,
                                       -0.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       0.0f),
            new ShaderNatives.float3x4(0.027779f, 0.0f, 0.001812f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 1.0f, 1.0f, 0.0f)
            ,
            new ShaderNatives.float3x4(0.025812f,
                                       -0.01398f,
                                       -0.027041f,
                                       0.0f,
                                       0.0f,
                                       0.0f,
                                       -0.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       0.0f),
            new ShaderNatives.float3x4(-0.03279f,
                                       0.0f,
                                       -0.000142f,
                                       0.0f,
                                       0.0f,
                                       -0.0f,
                                       0.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       0.0f),
            new ShaderNatives.float3x4(-0.01986f, 0.0f, 0.002514f, 0.0f, 0.0f, 0.0f, -0.0f, 1.0f, 1.0f, 1.0f, 1.0f, 0.0f)
            ,
            new ShaderNatives.float3x4(-0.027779f, 0.0f, 0.001812f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 1.0f, 1.0f, 0.0f)
            ,
            new ShaderNatives.float3x4(-0.025812f,
                                       -0.01398f,
                                       -0.027041f,
                                       0.0f,
                                       -0.0f,
                                       0.0f,
                                       -0.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       0.0f),
            new ShaderNatives.float3x4(0.022745f,
                                       0.0f,
                                       -0.000363f,
                                       0.0f,
                                       -0.0f,
                                       -0.0f,
                                       0.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       0.0f),
            new ShaderNatives.float3x4(0.020882f, 0.0f, 0.0018f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 1.0f, 1.0f, 0.0f),
            new ShaderNatives.float3x4(0.026793f,
                                       -0.01083f,
                                       -0.011936f,
                                       0.0f,
                                       0.0f,
                                       0.0f,
                                       0.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       0.0f),
            new ShaderNatives.float3x4(-0.022745f,
                                       0.0f,
                                       -0.000363f,
                                       0.0f,
                                       -0.0f,
                                       -0.0f,
                                       0.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       0.0f),
            new ShaderNatives.float3x4(-0.020881f, 0.0f, 0.0018f, 0.0f, -0.0f, -0.0f, 0.0f, 1.0f, 1.0f, 1.0f, 1.0f, 0.0f)
            ,
            new ShaderNatives.float3x4(-0.026793f,
                                       -0.01083f,
                                       -0.011936f,
                                       0.0f,
                                       0.0f,
                                       0.0f,
                                       0.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       0.0f),
            new ShaderNatives.float3x4(0.0f,
                                       -0.064901f,
                                       -0.117194f,
                                       0.0f,
                                       0.0f,
                                       0.0f,
                                       0.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       0.0f),
            new ShaderNatives.float3x4(0.0f,
                                       -0.064901f,
                                       -0.117194f,
                                       0.0f,
                                       0.0f,
                                       0.0f,
                                       0.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       0.0f),
            new ShaderNatives.float3x4(0.000301f,
                                       -0.024179f,
                                       -0.080161f,
                                       0.0f,
                                       0.0f,
                                       0.0f,
                                       0.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       0.0f),
            new ShaderNatives.float3x4(-0.036586f,
                                       0.019878f,
                                       -0.110888f,
                                       0.0f,
                                       0.0f,
                                       0.0f,
                                       -0.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       0.0f),
            new ShaderNatives.float3x4(-0.023027f,
                                       0.059438f,
                                       -0.121411f,
                                       0.0f,
                                       0.0f,
                                       -0.0f,
                                       -0.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       0.0f),
            new ShaderNatives.float3x4(-0.052751f,
                                       0.055098f,
                                       -0.105811f,
                                       0.0f,
                                       0.0f,
                                       0.0f,
                                       0.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       0.0f),
            new ShaderNatives.float3x4(-0.02656f,
                                       -0.023432f,
                                       -0.11549f,
                                       0.0f,
                                       0.0f,
                                       0.0f,
                                       0.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       0.0f),
            new ShaderNatives.float3x4(0.02656f,
                                       -0.023428f,
                                       -0.11549f,
                                       0.0f,
                                       0.0f,
                                       0.0f,
                                       0.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       0.0f),
            new ShaderNatives.float3x4(0.000131f,
                                       -0.018518f,
                                       -0.130177f,
                                       0.0f,
                                       0.0f,
                                       0.0f,
                                       0.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       0.0f),
            new ShaderNatives.float3x4(0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 1.0f, 1.0f, 0.0f),
            new ShaderNatives.float3x4(0.0f,
                                       -0.000655f,
                                       -0.120749f,
                                       0.0f,
                                       0.0f,
                                       0.0f,
                                       0.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       0.0f),
            new ShaderNatives.float3x4(0.036586f,
                                       0.019875f,
                                       -0.110888f,
                                       0.0f,
                                       0.0f,
                                       0.0f,
                                       0.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       0.0f),
            new ShaderNatives.float3x4(0.023027f,
                                       0.059443f,
                                       -0.121411f,
                                       0.0f,
                                       -0.0f,
                                       0.0f,
                                       0.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       0.0f),
            new ShaderNatives.float3x4(0.052751f,
                                       0.055099f,
                                       -0.105812f,
                                       0.0f,
                                       0.0f,
                                       0.0f,
                                       0.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       0.0f),
            new ShaderNatives.float3x4(-0.0342f,
                                       0.045557f,
                                       -0.097f,
                                       0.0f,
                                       0.0f,
                                       0.0f,
                                       0.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       0.0f),
            new ShaderNatives.float3x4(0.034197f, 0.045f, -0.097f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 1.0f, 1.0f, 0.0f)
            ,
            new ShaderNatives.float3x4(-0.0342f,
                                       0.045557f,
                                       -0.09f,
                                       0.0f,
                                       0.0f,
                                       -0.0f,
                                       0.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       0.0f),
            new ShaderNatives.float3x4(0.034197f, 0.045f, -0.09f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 1.0f, 1.0f, 0.0f),
            new ShaderNatives.float3x4(0.000136f,
                                       0.061297f,
                                       0.025088f,
                                       0.0f,
                                       -2.7e-005f,
                                       -1.2e-005f,
                                       -5.3e-005f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       0.0f),
            new ShaderNatives.float3x4(-0.0f,
                                       -0.119162f,
                                       0.063465f,
                                       0.0f,
                                       0.0f,
                                       0.0f,
                                       0.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       0.0f),
            new ShaderNatives.float3x4(-0.0f,
                                       0.262436f,
                                       -0.048258f,
                                       0.0f,
                                       0.0f,
                                       0.0f,
                                       0.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       0.0f),
            new ShaderNatives.float3x4(-0.0f,
                                       -0.046775f,
                                       -0.040397f,
                                       0.0f,
                                       0.0f,
                                       0.0f,
                                       0.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       0.0f),
            new ShaderNatives.float3x4(-0.0f,
                                       -0.050093f,
                                       -0.03263f,
                                       0.0f,
                                       0.0f,
                                       0.0f,
                                       -0.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       0.0f),
            new ShaderNatives.float3x4(0.069096f,
                                       -0.059014f,
                                       0.062435f,
                                       0.0f,
                                       0.0f,
                                       0.0f,
                                       0.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       0.0f),
            new ShaderNatives.float3x4(-0.004036f,
                                       -0.035372f,
                                       0.032719f,
                                       0.0f,
                                       0.0f,
                                       0.0f,
                                       0.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       1.0f,
                                       0.0f),
        };
    }
}
